services:
  - type: web
    name: clothing-website-backend
    env: node
    buildCommand: npm install && npm rebuild bcrypt --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
